# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Driver

    # The formatted phone number for contacting the driver.
    # @return [String]
    attr_accessor :phone_number

    # The driver's star rating out of 5 stars.
    # @return [Float]
    attr_accessor :rating

    # The URL to the photo of the driver.
    # @return [String]
    attr_accessor :picture_url

    # The first name of the driver.
    # @return [String]
    attr_accessor :name

    def initialize(phone_number = nil,
                   rating = nil,
                   picture_url = nil,
                   name = nil)
      @phone_number = phone_number
      @rating = rating
      @picture_url = picture_url
      @name = name

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        phone_number = hash["phone_number"]
        rating = hash["rating"]
        picture_url = hash["picture_url"]
        name = hash["name"]
        # Create object from extracted values
        Driver.new(phone_number,
                   rating,
                   picture_url,
                   name)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['phone_number'] = phone_number
      hash['rating'] = rating
      hash['picture_url'] = picture_url
      hash['name'] = name
      hash
    end
  end
end
