# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Errors

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    def initialize(status = nil,
                   code = nil,
                   title = nil)
      @status = status
      @code = code
      @title = title

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        status = hash["status"]
        code = hash["code"]
        title = hash["title"]
        # Create object from extracted values
        Errors.new(status,
                   code,
                   title)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['status'] = status
      hash['code'] = code
      hash['title'] = title
      hash
    end
  end
end
