# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Location

    # The address in user readable form
    # @return [String]
    attr_accessor :address

    # Latitude component of location.
    # @return [Float]
    attr_accessor :latitude

    # Longitude component of location.
    # @return [Float]
    attr_accessor :longitude

    def initialize(address = nil,
                   latitude = nil,
                   longitude = nil)
      @address = address
      @latitude = latitude
      @longitude = longitude

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        address = hash["address"]
        latitude = hash["latitude"]
        longitude = hash["longitude"]
        # Create object from extracted values
        Location.new(address,
                     latitude,
                     longitude)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['address'] = address
      hash['latitude'] = latitude
      hash['longitude'] = longitude
      hash
    end
  end
end
