# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Meta

    # TODO: Write general description for this method
    # @return [SurgeConfirmation]
    attr_accessor :surge_confirmation

    def initialize(surge_confirmation = nil)
      @surge_confirmation = surge_confirmation

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        surge_confirmation = SurgeConfirmation.from_hash(hash["surge_confirmation"])
        # Create object from extracted values
        Meta.new(surge_confirmation)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['surge_confirmation'] = surge_confirmation.key_map
      hash
    end
  end
end
