# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class PriceEstimateCollection

    # List of price estimates
    # @return [List of PriceEsitmate]
    attr_accessor :prices

    def initialize(prices = nil)
      @prices = prices

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        prices = nil
        if hash["prices"] != nil
          prices = Array.new
          hash["prices"].each{|structure| prices << PriceEsitmate.from_hash(structure)}
        end
        # Create object from extracted values
        PriceEstimateCollection.new(prices)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['prices'] = prices.map(&:key_map)
      hash
    end
  end
end
