# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class PriceEsitmate

    # Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
    # @return [String]
    attr_accessor :product_id

    # ISO 4217 currency code.
    # @return [String]
    attr_accessor :currency_code

    # Display name of product.
    # @return [String]
    attr_accessor :display_name

    # Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or "Metered" for TAXI.
    # @return [String]
    attr_accessor :estimate

    # Lower bound of the estimated price.
    # @return [Integer]
    attr_accessor :low_estimate

    # Upper bound of the estimated price.
    # @return [Integer]
    attr_accessor :high_estimate

    # Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier.
    # @return [Float]
    attr_accessor :surge_multiplier

    # Expected activity duration (in seconds). Always show duration in minutes.
    # @return [Integer]
    attr_accessor :duration

    # Expected activity distance (in miles).
    # @return [Float]
    attr_accessor :distance

    def initialize(product_id = nil,
                   currency_code = nil,
                   display_name = nil,
                   estimate = nil,
                   low_estimate = nil,
                   high_estimate = nil,
                   surge_multiplier = nil,
                   duration = nil,
                   distance = nil)
      @product_id = product_id
      @currency_code = currency_code
      @display_name = display_name
      @estimate = estimate
      @low_estimate = low_estimate
      @high_estimate = high_estimate
      @surge_multiplier = surge_multiplier
      @duration = duration
      @distance = distance

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        product_id = hash["product_id"]
        currency_code = hash["currency_code"]
        display_name = hash["display_name"]
        estimate = hash["estimate"]
        low_estimate = hash["low_estimate"]
        high_estimate = hash["high_estimate"]
        surge_multiplier = hash["surge_multiplier"]
        duration = hash["duration"]
        distance = hash["distance"]
        # Create object from extracted values
        PriceEsitmate.new(product_id,
                          currency_code,
                          display_name,
                          estimate,
                          low_estimate,
                          high_estimate,
                          surge_multiplier,
                          duration,
                          distance)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['product_id'] = product_id
      hash['currency_code'] = currency_code
      hash['display_name'] = display_name
      hash['estimate'] = estimate
      hash['low_estimate'] = low_estimate
      hash['high_estimate'] = high_estimate
      hash['surge_multiplier'] = surge_multiplier
      hash['duration'] = duration
      hash['distance'] = distance
      hash
    end
  end
end
