# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Product

    # Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
    # @return [String]
    attr_accessor :product_id

    # Description of product.
    # @return [String]
    attr_accessor :description

    # Display name of product.
    # @return [String]
    attr_accessor :display_name

    # Capacity of product. For example, 4 people.
    # @return [Integer]
    attr_accessor :capacity

    # Image URL representing the product.
    # @return [String]
    attr_accessor :image

    def initialize(product_id = nil,
                   description = nil,
                   display_name = nil,
                   capacity = nil,
                   image = nil)
      @product_id = product_id
      @description = description
      @display_name = display_name
      @capacity = capacity
      @image = image

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        product_id = hash["product_id"]
        description = hash["description"]
        display_name = hash["display_name"]
        capacity = hash["capacity"]
        image = hash["image"]
        # Create object from extracted values
        Product.new(product_id,
                    description,
                    display_name,
                    capacity,
                    image)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['product_id'] = product_id
      hash['description'] = description
      hash['display_name'] = display_name
      hash['capacity'] = capacity
      hash['image'] = image
      hash
    end
  end
end
