# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class PromotionsResponse

    # A localized string we recommend to use when offering the promotion to users.
    # @return [String]
    attr_accessor :display_text

    # The value of the promotion that is available to a user in this location in the local currency.
    # @return [String]
    attr_accessor :localized_value

    # The type of the promo which is either "trip_credit" or "account_credit".
    # @return [String]
    attr_accessor :type

    def initialize(display_text = nil,
                   localized_value = nil,
                   type = nil)
      @display_text = display_text
      @localized_value = localized_value
      @type = type

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        display_text = hash["display_text"]
        localized_value = hash["localized_value"]
        type = hash["type"]
        # Create object from extracted values
        PromotionsResponse.new(display_text,
                               localized_value,
                               type)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['display_text'] = display_text
      hash['localized_value'] = localized_value
      hash['type'] = type
      hash
    end
  end
end
