# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

require_relative 'error_base'

module UberApi
  class Request < ErrorBase 

    # The unique ID of the Request.
    # @return [String]
    attr_accessor :request_id

    # The status of the Request indicating state.
    # @return [String]
    attr_accessor :status

    # The object that contains vehicle details.
    # @return [Array<String, Object>]
    attr_accessor :vehicle

    # The object that contains driver details.
    # @return [Array<String, Object>]
    attr_accessor :driver

    # The object that contains the location information of the vehicle and driver
    # @return [Array<String, Object>]
    attr_accessor :location

    # The estimated time of vehicle arrival in minutes.
    # @return [Integer]
    attr_accessor :eta

    # The surge pricing multiplier used to calculate the increased price of a Request. A multiplier of 1.0 means surge pricing is not in effect.
    # @return [Float]
    attr_accessor :surge_multiplier

    def initialize(request_id = nil,
                   status = nil,
                   vehicle = nil,
                   driver = nil,
                   location = nil,
                   eta = nil,
                   surge_multiplier = nil,
                   meta = nil,
                   errors = nil)
      @request_id = request_id
      @status = status
      @vehicle = vehicle
      @driver = driver
      @location = location
      @eta = eta
      @surge_multiplier = surge_multiplier

      # Call the constructor for the base class
      super(meta,
            errors)

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        request_id = hash["request_id"]
        status = hash["status"]
        vehicle = hash["vehicle"]
        driver = hash["driver"]
        location = hash["location"]
        eta = hash["eta"]
        surge_multiplier = hash["surge_multiplier"]
        meta = hash["meta"]
        # Parameter is an array, so we need to iterate through it
        errors = nil
        if hash["errors"] != nil
          errors = Array.new
          hash["errors"].each{|structure| errors << Errors.from_hash(structure)}
        end
        # Create object from extracted values
        Request.new(request_id,
                    status,
                    vehicle,
                    driver,
                    location,
                    eta,
                    surge_multiplier,
                    meta,
                    errors)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['request_id'] = request_id
      hash['status'] = status
      hash['vehicle'] = vehicle
      hash['driver'] = driver
      hash['location'] = location
      hash['eta'] = eta
      hash['surge_multiplier'] = surge_multiplier
      hash = super().merge(hash) 
      hash
    end
  end
end
