# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class RequestDetailsCollections

    # The status of the Request indicating state.
    # @return [String]
    attr_accessor :status

    # The object that contains driver details.
    # @return [Driver]
    attr_accessor :driver

    # The estimated time of vehicle arrival in minutes.
    # @return [Integer]
    attr_accessor :eta

    # The object that contains the location information of the vehicle and driver.
    # @return [Location]
    attr_accessor :location

    # The object that contains vehicle details.
    # @return [Vehicle]
    attr_accessor :vehicle

    # The surge pricing multiplier used to calculate the increased price of a Request. A multiplier of 1.0 means surge pricing is not in effect.
    # @return [Float]
    attr_accessor :surge_multiplier

    # The unique ID of the Request.
    # @return [String]
    attr_accessor :request_id

    def initialize(status = nil,
                   driver = nil,
                   eta = nil,
                   location = nil,
                   vehicle = nil,
                   surge_multiplier = nil,
                   request_id = nil)
      @status = status
      @driver = driver
      @eta = eta
      @location = location
      @vehicle = vehicle
      @surge_multiplier = surge_multiplier
      @request_id = request_id

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        status = hash["status"]
        driver = Driver.from_hash(hash["driver"])
        eta = hash["eta"]
        location = Location.from_hash(hash["location"])
        vehicle = Vehicle.from_hash(hash["vehicle"])
        surge_multiplier = hash["surge_multiplier"]
        request_id = hash["request_id"]
        # Create object from extracted values
        RequestDetailsCollections.new(status,
                                      driver,
                                      eta,
                                      location,
                                      vehicle,
                                      surge_multiplier,
                                      request_id)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['status'] = status
      hash['driver'] = driver.key_map
      hash['eta'] = eta
      hash['location'] = location.key_map
      hash['vehicle'] = vehicle.key_map
      hash['surge_multiplier'] = surge_multiplier
      hash['request_id'] = request_id
      hash
    end
  end
end
