# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class RequestMapResponse

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :request_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :href

    def initialize(request_id = nil,
                   href = nil)
      @request_id = request_id
      @href = href

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        request_id = hash["request_id"]
        href = hash["href"]
        # Create object from extracted values
        RequestMapResponse.new(request_id,
                               href)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['request_id'] = request_id
      hash['href'] = href
      hash
    end
  end
end
