# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class SurgeConfirmation

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :href

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :surge_confirmation_id

    def initialize(href = nil,
                   surge_confirmation_id = nil)
      @href = href
      @surge_confirmation_id = surge_confirmation_id

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        href = hash["href"]
        surge_confirmation_id = hash["surge_confirmation_id"]
        # Create object from extracted values
        SurgeConfirmation.new(href,
                              surge_confirmation_id)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['href'] = href
      hash['surge_confirmation_id'] = surge_confirmation_id
      hash
    end
  end
end
