# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class TimeEstimateCollection

    # List of time estimates
    # @return [List of TimeEstimate]
    attr_accessor :times

    def initialize(times = nil)
      @times = times

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        times = nil
        if hash["times"] != nil
          times = Array.new
          hash["times"].each{|structure| times << TimeEstimate.from_hash(structure)}
        end
        # Create object from extracted values
        TimeEstimateCollection.new(times)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['times'] = times.map(&:key_map)
      hash
    end
  end
end
