# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class TimeEstimate

    # Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
    # @return [String]
    attr_accessor :product_id

    # Display name of product.
    # @return [String]
    attr_accessor :display_name

    # ETA for the product (in seconds). Always show estimate in minutes.
    # @return [Integer]
    attr_accessor :estimate

    def initialize(product_id = nil,
                   display_name = nil,
                   estimate = nil)
      @product_id = product_id
      @display_name = display_name
      @estimate = estimate

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        product_id = hash["product_id"]
        display_name = hash["display_name"]
        estimate = hash["estimate"]
        # Create object from extracted values
        TimeEstimate.new(product_id,
                         display_name,
                         estimate)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['product_id'] = product_id
      hash['display_name'] = display_name
      hash['estimate'] = estimate
      hash
    end
  end
end
