# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Vehicle

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :make

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :model

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :license_plate

    def initialize(make = nil,
                   model = nil,
                   license_plate = nil)
      @make = make
      @model = model
      @license_plate = license_plate

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        make = hash["make"]
        model = hash["model"]
        license_plate = hash["license_plate"]
        # Create object from extracted values
        Vehicle.new(make,
                    model,
                    license_plate)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['make'] = make
      hash['model'] = model
      hash['license_plate'] = license_plate
      hash
    end
  end
end
