# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require_relative 'uber_api/api_helper.rb'
require_relative 'uber_api/api_exception.rb'
require_relative 'uber_api/configuration.rb'
require_relative 'uber_api/uber_api_client.rb'

# Controllers
require_relative 'uber_api/controllers/api_controller.rb'

# Models
require_relative 'uber_api/models/product_collection.rb'
require_relative 'uber_api/models/price_estimate_collection.rb'
require_relative 'uber_api/models/time_estimate_collection.rb'
require_relative 'uber_api/models/location.rb'
require_relative 'uber_api/models/history.rb'
require_relative 'uber_api/models/user_activity.rb'
require_relative 'uber_api/models/user_profile.rb'
require_relative 'uber_api/models/promotions_response.rb'
require_relative 'uber_api/models/request.rb'
require_relative 'uber_api/models/error_base.rb'
require_relative 'uber_api/models/meta.rb'
require_relative 'uber_api/models/surge_confirmation.rb'
require_relative 'uber_api/models/errors.rb'
require_relative 'uber_api/models/vehicle.rb'
require_relative 'uber_api/models/request_map_response.rb'
require_relative 'uber_api/models/product.rb'
require_relative 'uber_api/models/time_estimate.rb'
require_relative 'uber_api/models/price_esitmate.rb'
require_relative 'uber_api/models/request_details_collections.rb'
require_relative 'uber_api/models/driver.rb'
require_relative 'uber_api/models/request_body.rb'
