# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016

module UberApi
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.uber.com/v1'

    # The OAuth 2.0 access token to be set before API calls
    @o_auth_access_token = TODO: Replace

    # create the getters and setters
    class << self
      attr_accessor :base_uri
      attr_accessor :o_auth_access_token
      attr_accessor :o_auth_access_token
    end
  end
end
